version: '3.8'

services:
  my_db_todolist:
    image: postgres:12.4-alpine
    volumes:
      - todolist_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports:
    - "5432:5432"

volumes:
  todolist_postgres_data:
